export const colors = [
  { id: 0, color: 'Black' },
  { id: 1, color: 'Blue' },
  { id: 2, color: 'Gray' },
  { id: 3, color: 'Green' },
  { id: 4, color: 'Maroon' },
  { id: 5, color: 'Red' },
  { id: 6, color: 'Silver' },
  { id: 7, color: 'White' },
];

export const makes = [
  { id: 0, make: 'Acura' },
  { id: 1, make: 'BMW' },
  { id: 2, make: 'Chevrolet' },
  { id: 3, make: 'Dodge' },
  { id: 4, make: 'Ford' },
  { id: 5, make: 'Mazda' },
  { id: 6, make: 'Mercedes-Benz' },
  { id: 7, make: 'Nissan' },
  { id: 8, make: 'Subaru' },
  { id: 9, make: 'Toyota' },
  { id: 10, make: 'Volkswagen' },
  { id: 11, make: 'Volvo' },
];

export const models = [
  { id: 0, model: 'Bronco Sport Big Bend' },
  { id: 1, model: 'Bronco Sport Outer Banks' },
  { id: 2, model: 'Caliber Express' },
  { id: 3, model: 'Camaro 1LT' },
  { id: 4, model: 'CC Sport' },
  { id: 5, model: 'C-Class C 300 4MATIC' },
  { id: 6, model: 'Colorado LT' },
  { id: 7, model: 'Colorado Z71' },
  { id: 8, model: 'Dart SE' },
  { id: 9, model: 'E-Class E 400 4MATIC' },
  { id: 10, model: 'Edge SEL' },
  { id: 11, model: 'Expedition Limited' },
  { id: 12, model: 'Expedition Max King Ranch' },
  { id: 13, model: 'Expedition Max XLT' },
  { id: 14, model: 'Expedition Platinum' },
  { id: 15, model: 'Expedition XLT' },
  { id: 16, model: 'Explorer Platinum' },
  { id: 17, model: 'Explorer XLT' },
  { id: 18, model: 'F-150 Platinum' },
  { id: 19, model: 'F-150 XL' },
  { id: 20, model: 'F-150 XLT' },
  { id: 21, model: 'Highlander Limited' },
  { id: 22, model: 'Highlander XLE' },
  { id: 23, model: 'Impreza WRX' },
  { id: 24, model: 'M3 Base' },
  { id: 25, model: 'Mazda3 i Touring' },
  { id: 26, model: 'RDX Technology Package' },
  { id: 27, model: 'S60 T6 Momentum' },
  { id: 28, model: 'Sequoia SR5' },
  { id: 29, model: 'Shelby GT350R Base' },
  { id: 30, model: 'Silverado 1500 Custom Trail Boss' },
  { id: 31, model: 'Tacoma SR5' },
  { id: 32, model: 'Tahoe LT' },
  { id: 33, model: 'Titan SL' },
  { id: 34, model: 'Titan XD SV' },
  { id: 35, model: 'TLX A-Spec' },
  { id: 36, model: 'Tundra Limited' },
  { id: 37, model: 'WRX Base' },
  { id: 38, model: 'WRX Premium' },
  { id: 39, model: 'WRX STI Base' },
];
