export const colors = [
  { id: 0, color: "Beige" },
  { id: 1, color: "Black" },
  { id: 2, color: "Blue" },
  { id: 3, color: "Brown" },
  { id: 4, color: "Caviar" },
  { id: 5, color: "Chalk" },
  { id: 6, color: "Glacier" },
  { id: 7, color: "Gold" },
  { id: 8, color: "Granite" },
  { id: 9, color: "Grey" },
  { id: 10, color: "Green" },
  { id: 11, color: "Ice" },
  { id: 12, color: "Maroon" },
  { id: 13, color: "Metallic" },
  { id: 14, color: "Onyx" },
  { id: 15, color: "Orange" },
  { id: 16, color: "Pink" },
  { id: 17, color: "Purple" },
  { id: 18, color: "Red" },
  { id: 19, color: "Rosso" },
  { id: 20, color: "Silver" },
  { id: 21, color: "Tan" },
  { id: 22, color: "Tempest" },
  { id: 23, color: "White" },
  { id: 24, color: "Yellow" },
  { id: 25, color: "Yulong" },
];
